---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c)
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: vind-task
spec:
  params:
    - name: vagrant_name
      description: name of the vagrant box to start
      default: default
      type: string
  resources:
    inputs:
      - name: repo
        type: git
        targetPath: src
  steps:
    - name: vagrant-up
      image: electrocucaracha/vind
      workingDir: /workspace/src/
      securityContext:
        privileged: true
        capabilities:
          add:
            - NET_ADMIN
      script: |
        source /libvirtd-lib.sh
        start_libvirtd

        sudo -E vagrant up $(params.vagrant_name)
